/**
 * Bibliography · single source for the /pt-PT/bibliografia/ page and EPUB
 * appendix. Each entry: { cite, url, type, section }.
 *
 * type ∈ paper | guideline | regulation | tool | wiki
 */

const ENTRIES = [
  // Papers · IA em saúde
  { cite: "Gulshan et al., 2015 (JAMA). Development and Validation of a Deep Learning Algorithm for Detection of Diabetic Retinopathy in Retinal Fundus Photographs.", url: "https://jamanetwork.com/journals/jama/fullarticle/2588763", section: "história · aprendizagem", type: "paper" },
  { cite: "Obermeyer et al., 2019 (Science). Dissecting racial bias in an algorithm used to manage the health of populations.", url: "https://www.science.org/doi/10.1126/science.aax2342", section: "vieses", type: "paper" },
  { cite: "Amugongo et al., 2025 (npj Digital Medicine). Retrieval-augmented generation in medicine — systematic review.", url: "https://www.nature.com/articles/s41746-025-01670-7", section: "rag", type: "paper" },
  { cite: "Bhayana et al., 2023 (Radiology). GPT-4 hallucination of citations.", url: "https://pubs.rsna.org/doi/10.1148/radiol.230922", section: "alucinações", type: "paper" },
  { cite: "Walters & Wilder, 2023 (JMIR). Fabrication and Errors in the Bibliographic Citations Generated by ChatGPT.", url: "https://www.jmir.org/2023/1/e48009", section: "alucinações", type: "paper" },
  { cite: "Singhal et al., 2023 (Nature). Med-PaLM 2: Large language models encode clinical knowledge.", url: "https://www.nature.com/articles/s41586-023-06291-2", section: "treino · aprofundar", type: "paper" },
  { cite: "Topol, 2019 (Nature Medicine). High-performance medicine: the convergence of human and artificial intelligence.", url: "https://www.nature.com/articles/s41591-018-0316-z", section: "aprofundar", type: "paper" },

  // Papers · fundamentos
  { cite: "Vaswani et al., 2017. Attention is all you need (Transformer paper).", url: "https://arxiv.org/abs/1706.03762", section: "história · funciona", type: "paper" },
  { cite: "Brown et al., 2020. GPT-3: Language Models are Few-Shot Learners.", url: "https://arxiv.org/abs/2005.14165", section: "história", type: "paper" },
  { cite: "Lewis et al., 2020. Retrieval-Augmented Generation for Knowledge-Intensive NLP Tasks.", url: "https://arxiv.org/abs/2005.11401", section: "rag", type: "paper" },
  { cite: "Rumelhart, Hinton & Williams, 1986. Learning representations by back-propagating errors.", url: "https://www.nature.com/articles/323533a0", section: "história", type: "paper" },
  { cite: "Krizhevsky, Sutskever & Hinton, 2012. ImageNet Classification with Deep Convolutional Neural Networks (AlexNet).", url: "https://papers.nips.cc/paper/2012/hash/c399862d3b9d6b76c8436e924a68c45b-Abstract.html", section: "história", type: "paper" },

  // Regulamentação
  { cite: "EU AI Act · Regulamento (UE) 2024/1689.", url: "https://eur-lex.europa.eu/eli/reg/2024/1689/oj", section: "privacidade", type: "regulation" },
  { cite: "RGPD · Regulamento (UE) 2016/679 (categoria especial: dados de saúde, art. 9).", url: "https://eur-lex.europa.eu/eli/reg/2016/679/oj", section: "privacidade", type: "regulation" },
  { cite: "CNPD · Comissão Nacional de Protecção de Dados.", url: "https://www.cnpd.pt/", section: "privacidade", type: "regulation" },
  { cite: "FDA · Lista oficial de dispositivos médicos com IA aprovados (1000+ em 2026, ~75% radiologia).", url: "https://www.fda.gov/medical-devices/software-medical-device-samd/artificial-intelligence-and-machine-learning-aiml-enabled-medical-devices", section: "história · privacidade", type: "regulation" },
  { cite: "IDx-DR · primeiro dispositivo IA aprovado pela FDA para diagnóstico autónomo (2018).", url: "https://www.fda.gov/news-events/press-announcements/fda-permits-marketing-artificial-intelligence-based-device-detect-certain-diabetes-related-eye", section: "história · aprendizagem", type: "regulation" },

  // Guidelines clínicas referidas
  { cite: "GINA 2024 · Global Initiative for Asthma. Recomendação MART/SMART para asma moderada.", url: "https://ginasthma.org/2024-report/", section: "rag", type: "guideline" },
  { cite: "DGS · Direcção-Geral da Saúde · normas e orientações clínicas para o SNS.", url: "https://www.dgs.pt/", section: "alucinações · aprofundar", type: "guideline" },
  { cite: "INFARMED · Autoridade nacional do medicamento.", url: "https://www.infarmed.pt/", section: "alucinações · aprofundar", type: "guideline" },

  // Ferramentas
  { cite: "Open Evidence · RAG sobre PubMed orientado a clínicos.", url: "https://www.openevidence.com/", section: "aprofundar", type: "tool" },
  { cite: "Glass Health · apoio à decisão para diferenciais e planos clínicos.", url: "https://glass.health/", section: "aprofundar", type: "tool" },
  { cite: "Elicit · RAG para revisão de literatura.", url: "https://elicit.com/", section: "aprofundar", type: "tool" },
  { cite: "NEJM AI · revista dedicada a IA em medicina (2024+).", url: "https://ai.nejm.org/", section: "aprofundar", type: "tool" },
  { cite: "Claude.ai · modelo de fronteira da Anthropic.", url: "https://claude.ai/", section: "aprofundar", type: "tool" },
  { cite: "ChatGPT · OpenAI.", url: "https://chatgpt.com/", section: "aprofundar", type: "tool" },
  { cite: "Gemini · Google.", url: "https://gemini.google.com/", section: "aprofundar", type: "tool" },
  { cite: "3Blue1Brown · Neural Networks (visualização matemática).", url: "https://www.3blue1brown.com/lessons/neural-networks", section: "aprofundar", type: "tool" },
  { cite: "Transformer Circuits · Anthropic (mecanismos internos dos LLMs).", url: "https://transformer-circuits.pub/", section: "aprofundar", type: "tool" },

  // Wikipedia
  { cite: "ELIZA (1966) · Wikipedia.", url: "https://en.wikipedia.org/wiki/ELIZA", section: "história", type: "wiki" },
  { cite: "MYCIN (1972) · Wikipedia.", url: "https://en.wikipedia.org/wiki/Mycin", section: "história", type: "wiki" },
  { cite: "Perceptron (1958) · Wikipedia.", url: "https://en.wikipedia.org/wiki/Perceptron", section: "história", type: "wiki" },
  { cite: "Minsky & Papert · Perceptrons (1969).", url: "https://en.wikipedia.org/wiki/Perceptrons_(book)", section: "história", type: "wiki" },
  { cite: "Deep Blue (1997) · Wikipedia.", url: "https://en.wikipedia.org/wiki/Deep_Blue_(chess_computer)", section: "história", type: "wiki" },
];

const GROUPS = {
  paper: { label: "Papers", icon: "📄" },
  guideline: { label: "Guidelines clínicas", icon: "🩺" },
  regulation: { label: "Regulamentação", icon: "⚖️" },
  tool: { label: "Ferramentas e leituras", icon: "🛠" },
  wiki: { label: "Conceitos (Wikipedia)", icon: "📖" },
};

function toBibTex(entries) {
  return entries
    .map((e, idx) => {
      const key = `iasaude${idx}`;
      const title = (e.cite.split(".")[0] || "Untitled").trim();
      return `@misc{${key},\n  title = {${title}},\n  url = {${e.url}}\n}`;
    })
    .join("\n\n");
}

export default {
  entries: ENTRIES,
  groups: GROUPS,
  bibText: toBibTex(ENTRIES),
};
